name: Website Linter

on:
  pull_request:
    paths:
      - 'src/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 21.x

    - name: Set up pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 9.11.0

    - name: Install dependencies
      run: |
        pnpm install

    - name: Build
      run: pnpm run build

    - name: Test
      run: pnpm run lint